# Generated by Django 4.2.6 on 2023-10-17 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InstructionRu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('send_hash', models.CharField(blank=True, max_length=150, verbose_name='Отправленый код проверки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Отправленный код для верификации',
                'verbose_name_plural': 'Отправленные коды для верификации',
            },
        ),
    ]
