# Generated by Django 4.2.6 on 2023-10-17 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BotVerification', '0002_rename_instructionru_verificationcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='verificationcode',
            name='email',
            field=models.CharField(blank=True, max_length=100, verbose_name='Email'),
        ),
    ]
